services:
  APP:
    image: node:lts-alpine3.20
    command: sh -c "npm i && npm run dev"
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3002:3002

  DB:
    image: mongo:7.0.5-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_DATABASE: gamedb

volumes:
  mongo-data: